spring:
  datasource:
    url: jdbc:mysql://localhost:13306/vhr?useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456

server:
  port: 8081

#开启mybatis日志，能看到SQL语句
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl