spring:
  datasource:
    url: jdbc:mysql://localhost:13306/vhr?useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456