server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/vhr?useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456

#开启mybatis日志，能看到SQL语句
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  #合法性(纠错机制)，为true时，pageNum <= 0 会查询第一页，pageNum > pages 会查询最后一页。
  reasonable: true
  #支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动从@params配置的字段中取值，查找到合适的值就会自动分页。
  support-methods-arguments: true

rocketmq:
  name-server: 43.138.236.83:9876
  producer:
    group: pg_vhr


#常用的固定信息
error-data-excel-file-path: D:\workspace\vhr\error-data-files\
regex-info:
  dateRegex: ^((?!0000)[0-9]{4}-((0[1-9]|1[0-2])-(0[1-9]|1[0-9]|2[0-8])|(0[13-9]|1[0-2])-(29|30)|(0[13578]|1[02])-31)|([0-9]{2}(0[48]|[2468][048]|[13579][26])|(0[48]|[2468][048]|[13579][26])00)-02-29)$
  idCardRegex: ^[1-9]\d{5}(18|19|20)\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\d{3}[0-9Xx]$
  phoneRegex: ^1[3-9]\d{9}$
  emailRegex: ^[a-zA-Z1-9]([a-zA-Z0-9]*[-_]?[a-zA-Z0-9]+)*@[a-zA-Z1-9]([a-zA-Z0-9]*[-_]?[a-zA-Z0-9]+)*[\.][a-zA-Z]{2,3}([\.][a-zA-Z]{2,3})*$
employee-fixed-info:
  errorDataFilePath: ${error-data-excel-file-path}
  genderInfo: [ 男,女 ]
  wedlockInfo: [ 未婚,已婚,离异 ]
  highestDegreeInfo: [ 博士,硕士,本科,大专,高中,初中,小学,其他 ]
  engageFormInfo: [ 劳动合同,劳务合同 ]
  workStatusInfo: [ 在职,离职 ]
mail-producer-info:
  topic: topic_mail
  tagWelcome: tag_welcome
# nginx访问地址
fastdfs:
  # Nginx服务器地址
  nginxHost: http://192.168.148.100/
  # fastdfs-client.properties配置文件 的 fastdfs.http_secret_key
  httpSecretKey: FastDFS1234567890
